modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU GPL 3.0"
issueTrackerURL = "https://github.com/btmluiz/cloudbackup/issues"
[[mods]]
modId = "cloudbackup"
version = "${version}"
displayName = "cloudbackup"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cloudbackup"
logoFile = "icon.png"
authors="Luiz Braga"
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
description = '''

'''
[[dependencies.cloudbackup]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.cloudbackup]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "CLIENT"
