modLoader = "javafml" #mandatory
loaderVersion = "[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LGPL 3.0"
issueTrackerURL = "https://github.com/btmluiz/cloudbackup/issues"
[[mods]]
authors = "Luiz Braga"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cloudbackup"
modId = "cloudbackup" #mandatory
version = "${version}" #mandatory
displayName = "cloudbackup" #mandatory
logoFile = "icon.png" #optional
description = '''

'''
[[dependencies.cloudbackup]]
modId = "forge"
mandatory = true
versionRange = "[38,)
ordering = "NONE"
side = "CLIENT"
[[dependencies.cloudbackup]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "CLIENT"
