modLoader = "javafml"
loaderVersion = "[41,)"
license = "GNU GPL 3.0"
issueTrackerURL = "https://github.com/btmluiz/cloudbackup/issues"
[[mods]]
modId = "cloudbackup"
version = "${version}"
displayName = "cloudbackup"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cloudbackup"
logoFile = "icon.png"
authors="Luiz Braga"
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
description = '''
Automatically back up your Minecraft world and upload it to cloud services like Google Drive and Dropbox with CloudBackup.
This mod features customizable settings for enabling/disabling backups and automatic uploads.
Keep your Minecraft world safe and secure with CloudBackup.
'''
[[dependencies.cloudbackup]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.cloudbackup]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.cloudbackup]]
modId = "cloth_config"
mandatory = true
versionRange = "[9,)"
ordering = "NONE"
side = "CLIENT"