name: Bug report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us reproduce and fix the bug as quickly as possible.
  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or use the upload button
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help explain your problem. You can find them in the `.minecraft/logs/latest.log` folder.
      placeholder: Drag and drop files here or use the upload button
    validations:
      required: false
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: The version of Minecraft you are using.
      placeholder: Ex. 1.20.2
    validations:
      required: true
  - type: input
    id: cloudbackup-version
    attributes:
      label: CloudBackup version
      description: The version of CloudBackup you are using.
      placeholder: Ex. 1.0.0
  - type: input
    id: os
    attributes:
      label: Operating system
      description: The operating system you are using.
      placeholder: Ex. Windows 10
    validations:
      required: true
  - type: checkboxes
    id: loader
    attributes:
      label: Loader
      description: The loader you are using.
      options:
        - label: Fabric
        - label: Forge
  - type: input
    id: loader-version
    attributes:
      label: Loader version
      description: The version of the loader you are using.
      placeholder: 1.0.0